### ISSUE TITLE
Name issue?

### ISSUE THREAD

**Issue by ghost** [jtaby/Waldo#4]
I'm not able to install it.  I tried the latest download but it doesn't include Waldo.app as described in the Readme.md, just VimAck.app.  Installing and running VimAck.app doesn't seem to work - leader-f does nothing.

**Comment by jtaby** [comment]
I just pushed up Waldo-0.3.zip please try downloading it and following the Usage instructions. Let me know if you continue to have problems

https://github.com/downloads/jtaby/Waldo/Waldo-0.3.zip

**Comment by ghost** [comment]
Thanks.  That worked, though I had to add a "Bundle 'Waldo'" line to my _vimrc.  Perhaps its a vundle requirement to have the line?

**Comment by jtaby** [comment]
Thanks for the comment, I've reopened the issue so I can track down the problem.

**Comment by jtaby** [comment]
@psheill Do you have  `call pathogen#runtime_append_all_bundles()` in your .vimrc file?

**Comment by ghost** [comment]
No I don't.  I've been using Vundle, not pathogen.  That must be the issue.  Thanks.
