### ISSUE TITLE
Add ability to make files open in tabs instead of new MacVim window

### ISSUE THREAD

**Issue by durden** [jtaby/Waldo#9]
Does this already exist?  I'm not familiar with developing Mac applications, and I don't see any obvious ways to configure this.  Maybe there could be a variable set in the Waldo.vim to allow for setting the default 'open' option, or even a checkbox in the main Waldo view that determines whether you want to open in a new tab or window.

**Comment by jtaby** [comment]
You can change the preference in MacVim to define how new files are opened. It's the "Open files from applications:" option.

**Comment by durden** [comment]
Ah ha!  That makes sense.  I never changed that setting b/c I usually open files with my own key mapping and keyboard shortcut, not the open dialogue.  Thanks!
